### ISSUE TITLE
How to send multiple values simultaneously from client to server and store in database

### ISSUE THREAD

**Issue by Mrahmani71** [tanishqmanuja/todos-react-elysia#1]
Hello,

Thank you for creating this useful project. I have a question about the application's functionality:

How can we simultaneously receive multiple values (for example, 10 values) from the client side, send them to the server, and then store them in the database?

Please advise on the best approach to implement this feature.

Thank you

**Comment by tanishqmanuja** [comment]
Depends on the use case, can you explain little more

**Comment by Mrahmani71** [comment]
In my project, I have a form where I want to collect multiple tags (for example, 10 tags) simultaneously and send them to the server. Similarly, in your project, we might want to send 20 todo activities simultaneously from the client to the server and add all of them to the database.

Thank you

**Comment by tanishqmanuja** [comment]
You can do the change in server's todos route file and make the post handler accept an array of todos and then add them to the database. The database already accepts multiple values at once, so no issue there.

Something like this
```typescript
	.post(
		"/",
		async ({ body }) => {
			const todosToAdd = body.map((todo) => ({ id: crypto.randomUUID(), ...todo }));

			return db
				.insert(todos)
				.values(todosToAdd)
				.returning();
		},
		{
			body: t.Array(withoutId(TodoInsertSchema)),
		},
	)
```

**Comment by Mrahmani71** [comment]
Thank you for your guidance. I apologize for replying late. 💐
